name: gym
description: "health care project"
publish_to: 'none'
version: 1.0.0+1

#=========================================================================

environment:
  sdk: ^3.5.1

#=========================================================================

dependencies:
  flutter:
    sdk: flutter

  #++++++   P A C K A G E S  +++++++++
  cupertino_icons: 
  provider:
  animated_text_kit:
  table_calendar:
  fl_chart:
  swiping_card_deck:
  carousel_slider: 
  intl:

#=========================================================================

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

#=========================================================================

flutter:
  uses-material-design: true

  assets:
    - assets/

#=========================================================================